#
# Makefile
#

DOCUMENT = MetalProgrammingBasics.md

SECTIONS = \
	001-Introduction.md \
	002-SoftwareComponents.md \
	003-BasicSequence.md  \
	100-Tips.md \
	101-References.md

all: $(DOCUMENT)


$(DOCUMENT): $(SECTIONS)
	cat $(SECTIONS) > $(DOCUMENT)

