#
# Makefile
#

DOCUMENT = MetalProgrammingBasics.md

SECTIONS = \
	001-Introduction.md \
	002-SoftwareComponents.md \
	100-References.md

all: $(DOCUMENT)


$(DOCUMENT): $(SECTIONS)
	cat $(SECTIONS) > $(DOCUMENT)

